language: java

script: echo "yoooo"

before_install:
  - sudo apt-get update
  - sudo apt-get install python

install:
  - pip install --user bumpversion
  - npm install @semantic-release/exec

deploy:
  provider: script
  skip_cleanup: true
  script:
    - nvm install lts/*
    - npx travis-deploy-once "npx semantic-release"
