language: java
sudo: required

before_install:
  - pip install bumpversion

script: echo "yoooo"

deploy:
  provider: script
  skip_cleanup: true
  script:
    - nvm install lts/*
    - npx travis-deploy-once "npx semantic release"
